name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [main]
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: "latest"

      - name: Install dependencies
        run: pnpm install

      - name: Run check
        run: pnpm --filter frontend astro -- check

      - name: Build
        run: pnpm --filter frontend build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: "./firebase"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASTRO_FIREBASE_STARTER }}"
          channelId: live
          projectId: astro-firebase-starter
